version: '3'
services:
  app:
    environment:
      - MONGO_URI=mongo:27017
      - MONGO_DB_NAME=project
      - PORT=9000
      - ENCRYPTION_PRIVATE_KEY_PATH=scripts/enc.key
      - TOKEN_EXPIRY=60
    build: .
    command: npm run test:integration
    depends_on: 
      - "mongo"
  mongo:
    image: "mongo"